import { router } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { Text, View } from 'react-native';

import { CustomerButton, CustomerCard, CustomerHeading, CustomerPage, CustomerState } from '@/components/customer/customer-ui';
import { useGuestFlow } from '@/features/public/guest-flow-session';
import { canUseGuestTicket } from '@/features/public/public-route-policy';
import { cancelGuestTicket, getGuestTicketState, type GuestTicketState } from '@/features/queue/public-guest-ticket-api';
import { canCancelTicket, presentTicketStatus, ticketPosition } from '@/features/queue/ticket-presentation';
import { translateQueueError } from '@/features/queue/queue-api';
import { useTheme } from '@/hooks/use-theme';

export default function GuestTicketScreen() {
  const theme = useTheme(); const { ticketAccess, reset } = useGuestFlow(); const [ticket, setTicket] = useState<GuestTicketState | null>(null); const [error, setError] = useState<string | null>(null); const [isLoading, setIsLoading] = useState(true); const [isCancelling, setIsCancelling] = useState(false);
  const refresh = useCallback(async () => { if (!ticketAccess) return; setIsLoading(true); try { setTicket(await getGuestTicketState(ticketAccess)); setError(null); } catch (reason) { setError(translateQueueError(reason instanceof Error ? reason.message : '')); } finally { setIsLoading(false); } }, [ticketAccess]);
  useEffect(() => { void refresh(); }, [refresh]);
  if (!canUseGuestTicket(ticketAccess)) return <CustomerPage><CustomerState label="No hay un turno disponible en esta sesión." detail="Por privacidad, necesitas conservar el acceso del turno en este dispositivo." action={() => router.replace('/')} /></CustomerPage>;
  const status = ticket ? presentTicketStatus(ticket.status) : null; const canCancel = ticket ? canCancelTicket(ticket.status) : false;
  async function cancel() { if (!ticketAccess || !canCancel) return; setIsCancelling(true); try { await cancelGuestTicket(ticketAccess); await refresh(); } catch (reason) { setError(translateQueueError(reason instanceof Error ? reason.message : '')); } finally { setIsCancelling(false); } }
  return <CustomerPage><CustomerHeading eyebrow="Turno confirmado" title="Tu código de atención" detail="Conserva este código mientras esperas. No permite recuperar el turno por sí solo." />{isLoading && <CustomerState label="Actualizando tu turno…" isLoading />}{error && <CustomerState label={error} action={() => void refresh()} />}{ticket && status && <><CustomerCard style={{ alignItems: 'center', gap: 8, paddingVertical: 24 }}><Text style={{ color: theme.textSecondary, fontSize: 11, fontWeight: '700', letterSpacing: 1 }}>CÓDIGO</Text><Text style={{ color: theme.text, fontSize: 56, fontWeight: '800' }}>{ticket.visibleCode}</Text><Text style={{ color: theme.primary, fontWeight: '700' }}>{status.label.toUpperCase()}</Text><Text style={{ color: theme.textSecondary, textAlign: 'center' }}>{status.message}</Text></CustomerCard>{status.showsQueueProgress && <CustomerCard><Text style={{ color: theme.text, fontWeight: '700' }}>Progreso de la fila</Text><View style={{ flexDirection: 'row', gap: 12, marginTop: 12 }}><View style={{ backgroundColor: theme.primaryMuted, borderRadius: 12, flex: 1, padding: 14 }}><Text style={{ color: theme.text, fontSize: 24, fontWeight: '700' }}>{ticketPosition(ticket.peopleAhead)}</Text><Text style={{ color: theme.textSecondary }}>posición</Text></View><View style={{ backgroundColor: theme.primaryMuted, borderRadius: 12, flex: 1, padding: 14 }}><Text style={{ color: theme.text, fontSize: 24, fontWeight: '700' }}>{ticket.waitMinutes} min</Text><Text style={{ color: theme.textSecondary }}>espera estimada</Text></View></View></CustomerCard>}{(ticket.serviceName || ticket.requestedBarberName || ticket.assignedBarberName) && <CustomerCard><Text style={{ color: theme.text, fontWeight: '700' }}>Detalles</Text>{ticket.serviceName && <Text style={{ color: theme.textSecondary, marginTop: 8 }}>Servicio · {ticket.serviceName}</Text>}{ticket.requestedBarberName && <Text style={{ color: theme.textSecondary, marginTop: 4 }}>Preferencia · {ticket.requestedBarberName}</Text>}{ticket.assignedBarberName && <Text style={{ color: theme.textSecondary, marginTop: 4 }}>Barbero asignado · {ticket.assignedBarberName}</Text>}</CustomerCard>}{canCancel && <CustomerButton label="Cancelar turno" variant="destructive" disabled={isCancelling} loading={isCancelling} onPress={() => void cancel()} />}<CustomerButton label="Actualizar" variant="secondary" onPress={() => void refresh()} /><CustomerButton label="Finalizar" variant="secondary" onPress={() => { reset(); router.replace('/'); }} /></>}</CustomerPage>;
}
