import { router, useLocalSearchParams } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { Text, View } from 'react-native';
import { CustomerScreenContainer } from '@/components/customer/customer-screen-container';
import { ChoiceCard, CustomerButton, CustomerCard, CustomerHeading, CustomerPage, CustomerState } from '@/components/customer/customer-ui';
import { useTheme } from '@/hooks/use-theme';
import { bookingExpectation, compatibleBarbers, formatReferencePrice, selectedBarber, type BarberChoice } from '@/features/queue/commercial-booking';
import { getCommercialCatalog, takeCommercialTurn, type CommercialCatalog } from '@/features/queue/commercial-queue-api';
import { normalizeBusinessCode, translateQueueError } from '@/features/queue/queue-api';

export default function PreviewScreen() {
  const theme = useTheme(); const { code: rawCode } = useLocalSearchParams<{ code?: string }>(); const code = normalizeBusinessCode(rawCode ?? '');
  const [catalog, setCatalog] = useState<CommercialCatalog | null>(null); const [selectedServiceId, setSelectedServiceId] = useState<string | null>(null); const [barberChoice, setBarberChoice] = useState<BarberChoice | null>(null); const [error, setError] = useState<string | null>(null); const [isLoading, setIsLoading] = useState(true); const [isTakingTurn, setIsTakingTurn] = useState(false);
  const loadCatalog = useCallback(async () => { if (!code) { setError('El código de empresa no es válido.'); setIsLoading(false); return; } setIsLoading(true); setError(null); try { setCatalog(await getCommercialCatalog(code)); setSelectedServiceId(null); setBarberChoice(null); } catch (reason) { setError(translateQueueError(reason instanceof Error ? reason.message : '')); } finally { setIsLoading(false); } }, [code]);
  useEffect(() => { void loadCatalog(); }, [loadCatalog]);
  const selectedService = catalog?.services.find((service) => service.serviceId === selectedServiceId) ?? null; const compatible = catalog ? compatibleBarbers(catalog, selectedServiceId) : []; const chosenBarber = selectedBarber(compatible, barberChoice); const canSubmit = Boolean(catalog?.open && selectedService && barberChoice && !isTakingTurn);
  async function handleTakeTurn() { if (!code || !selectedService || !barberChoice) return; setIsTakingTurn(true); setError(null); try { const ticket = await takeCommercialTurn({ companyCode: code, serviceId: selectedService.serviceId, requestedBarberId: barberChoice.kind === 'named' ? barberChoice.barberId : null }); router.replace({ pathname: '/(app)/ticket', params: { ticketId: ticket.ticketId, queueId: ticket.queueId } }); } catch (reason) { setError(translateQueueError(reason instanceof Error ? reason.message : '')); } finally { setIsTakingTurn(false); } }
  return <CustomerScreenContainer activeNavigation="home"><CustomerPage><CustomerHeading eyebrow="Solicitar turno" title={catalog?.name ?? 'Buscando barbería'} detail="Elige un servicio y cómo prefieres atenderte." />
    {isLoading && <CustomerState label="Consultando la barbería…" isLoading />}{error && <CustomerState label={error} action={() => void loadCatalog()} />}
    {catalog && <><CustomerCard><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><Text style={{ color: theme.text, fontSize: 18, fontWeight: '700' }}>{catalog.name}</Text><Text style={{ color: catalog.open ? theme.success : theme.destructive, fontWeight: '700' }}>{catalog.open ? 'ABIERTA' : 'CERRADA'}</Text></View><Text style={{ color: theme.textSecondary, marginTop: 8 }}>{catalog.open ? 'La fila se actualiza con el ritmo real del equipo.' : 'Esta barbería no recibe turnos ahora.'}</Text></CustomerCard>
      <CustomerHeading eyebrow="Paso 1 de 2" title="Elige tu servicio" />{catalog.services.length === 0 && <CustomerState label="No hay servicios activos disponibles." />}{catalog.services.map((service) => <ChoiceCard key={service.serviceId} title={service.name} selected={selectedServiceId === service.serviceId} disabled={isTakingTurn || !catalog.open} onPress={() => { setSelectedServiceId(service.serviceId); setBarberChoice(null); }} detail={`${Math.ceil(service.estimatedDurationSeconds / 60)} min${formatReferencePrice(service.referencePriceCents) ? ` · Referencia ${formatReferencePrice(service.referencePriceCents)}` : ''}${service.description ? `\n${service.description}` : ''}`} />)}
      {selectedService && <><CustomerHeading eyebrow="Paso 2 de 2" title="Elige tu barbero" detail={`${selectedService.name} · ${Math.ceil(selectedService.estimatedDurationSeconds / 60)} min`} /><ChoiceCard title="Cualquier barbero disponible" badge="Menor espera" detail="La opción más rápida según la compatibilidad del servicio." selected={barberChoice?.kind === 'any'} disabled={isTakingTurn || !catalog.open} onPress={() => setBarberChoice({ kind: 'any' })} />{compatible.map((barber) => <ChoiceCard key={barber.barberId} title={barber.name} detail={barber.operationalState === 'ocupado' ? 'Atendiendo ahora; puedes elegirlo y esperar su disponibilidad.' : 'Disponible para este servicio.'} selected={barberChoice?.kind === 'named' && barberChoice.barberId === barber.barberId} disabled={isTakingTurn || !catalog.open} onPress={() => setBarberChoice({ kind: 'named', barberId: barber.barberId })} />)}{compatible.length === 0 && <CustomerState label="No hay barberos compatibles en turno." />}</>}
      {selectedService && barberChoice && <CustomerCard><Text style={{ color: theme.text, fontWeight: '700' }}>Confirma tu turno</Text><Text style={{ color: theme.textSecondary, marginTop: 6 }}>{selectedService.name} · {chosenBarber?.name ?? 'Cualquier barbero disponible'}</Text><Text style={{ color: theme.textSecondary, marginTop: 6 }}>{bookingExpectation(selectedService, chosenBarber)}</Text></CustomerCard>}<CustomerButton label="Confirmar turno" disabled={!canSubmit} loading={isTakingTurn} onPress={() => void handleTakeTurn()} /></>}
    <CustomerButton label="Volver" variant="secondary" disabled={isTakingTurn} onPress={() => router.back()} /></CustomerPage></CustomerScreenContainer>;
}
