import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';

import { WorkerButton, WorkerIcon, WorkerPill, WorkerText, workerColors, workerUiStyles } from '@/components/worker/worker-ui';
import { WorkerScreenContainer } from '@/components/worker/worker-screen-container';
import { createMyWalkInTicket, getWorkerQueues } from '@/features/queue/worker-barber-api';

export default function WorkerWalkInScreen() {
  const [queues, setQueues] = useState<Array<{ queueId: string; name: string }>>([]); const [queueId, setQueueId] = useState<string | null>(null); const [name, setName] = useState(''); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const load = useCallback(() => { void getWorkerQueues().then((next) => { setQueues(next); setQueueId((current) => current && next.some((queue) => queue.queueId === current) ? current : next[0]?.queueId ?? null); }).catch(() => setError('No pudimos cargar las filas de la barbería seleccionada.')); }, []); useFocusEffect(load);
  async function submit() { if (!queueId) return; setLoading(true); setError(null); try { setNotice(`Turno creado: ${await createMyWalkInTicket(queueId, name)}`); setName(''); } catch { setError('No pudimos crear el turno presencial. Verifica la barbería seleccionada e intenta nuevamente.'); } finally { setLoading(false); } }
  return <WorkerScreenContainer activeNavigation="live"><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={workerUiStyles.page}><View style={styles.top}><Pressable accessibilityRole="button" accessibilityLabel="Cerrar registro presencial" onPress={() => router.back()}><WorkerIcon name="close" /></Pressable><WorkerPill label="15 SEGUNDOS" tone="teal" /></View><View style={styles.heading}><WorkerText variant="eyebrow" color={workerColors.teal}>Registro rápido</WorkerText><WorkerText variant="title">Cliente presencial</WorkerText><WorkerText color={workerColors.muted}>Crea un turno con la posición real que defina la cola.</WorkerText></View><View style={styles.speed}><WorkerIcon name="check" color={workerColors.teal} /><WorkerText variant="label">Solo nombre y servicio para asignar.</WorkerText></View><View style={workerUiStyles.card}><WorkerText variant="label">Nombre del cliente</WorkerText><TextInput accessibilityLabel="Nombre del cliente" value={name} onChangeText={setName} editable={!loading} placeholder="Ej. Carlos Méndez" placeholderTextColor={workerColors.muted} style={styles.input} /><WorkerText variant="label">Servicio disponible</WorkerText><View style={styles.options}>{queues.map((queue) => <Pressable key={queue.queueId} accessibilityRole="radio" accessibilityState={{ selected: queue.queueId === queueId }} onPress={() => setQueueId(queue.queueId)} style={[styles.option, { backgroundColor: queue.queueId === queueId ? workerColors.ink : workerColors.low, borderColor: queue.queueId === queueId ? workerColors.ink : workerColors.outline }]}><WorkerText variant="label" color={queue.queueId === queueId ? '#FFFFFF' : workerColors.body}>{queue.name}</WorkerText>{queue.queueId === queueId && <WorkerIcon name="check" color="#FFFFFF" />}</Pressable>)}</View>{queues.length === 0 && <WorkerText color={workerColors.muted}>No hay servicios compatibles disponibles para asignar.</WorkerText>}<WorkerButton label="Asignar turno" disabled={!queueId || !name.trim() || loading} onPress={() => void submit()} /></View>{notice && <View accessibilityRole="alert" style={workerUiStyles.card}><WorkerText variant="label" color={workerColors.teal}>{notice}</WorkerText></View>}{error && <View style={[workerUiStyles.card, { backgroundColor: workerColors.errorContainer }]}><WorkerText color={workerColors.error}>{error}</WorkerText></View>}</ScrollView></WorkerScreenContainer>;
}
const styles = StyleSheet.create({ top: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, heading: { gap: 6 }, speed: { alignItems: 'center', backgroundColor: workerColors.tealContainer, borderRadius: 8, flexDirection: 'row', gap: 8, padding: 12 }, input: { backgroundColor: workerColors.low, borderColor: workerColors.outline, borderRadius: 8, borderWidth: 1, color: workerColors.body, fontFamily: 'Work Sans', fontSize: 16, minHeight: 52, paddingHorizontal: 12 }, options: { gap: 8 }, option: { alignItems: 'center', borderRadius: 8, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 52, paddingHorizontal: 12 } });
