import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, View } from 'react-native';

import { WorkerButton, WorkerPill, WorkerText, workerColors, workerUiStyles } from '@/components/worker/worker-ui';
import { WorkerScreenContainer } from '@/components/worker/worker-screen-container';
import { callMyNextTicket, getWorkerBarberQueue, translateWorkerBarberError, type WorkerTicket } from '@/features/queue/worker-barber-api';

export default function WorkerQueueScreen() {
  const [tickets, setTickets] = useState<WorkerTicket[]>([]); const [availability, setAvailability] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [isLoading, setIsLoading] = useState(true); const [isCalling, setIsCalling] = useState<string | null>(null);
  const refresh = useCallback(async () => { if (process.env.EXPO_PUBLIC_SKIP_AUTH === '1') { setAvailability('disponible'); setTickets([{ ticketId: 't2', queueId: 'q1', queueName: 'Cortes', visibleCode: 'A25', state: 'notificado', serviceName: 'Corte clásico', requestedBarberName: 'Carlos', assignedBarberName: null, calledDeadlineAt: null, customerResponse: null, customerResponseAt: null }, { ticketId: 't3', queueId: 'q2', queueName: 'Barba', visibleCode: 'B11', state: 'en_espera', serviceName: 'Perfilado de barba', requestedBarberName: null, assignedBarberName: null, calledDeadlineAt: null, customerResponse: null, customerResponseAt: null }, { ticketId: 't4', queueId: 'q1', queueName: 'Cortes', visibleCode: 'A26', state: 'en_espera', serviceName: 'Afeitado clásico', requestedBarberName: null, assignedBarberName: null, calledDeadlineAt: null, customerResponse: null, customerResponseAt: null }]); setError(null); setIsLoading(false); return; } setIsLoading(true); try { const queue = await getWorkerBarberQueue(); setAvailability(queue.availability); setTickets(queue.tickets.filter((ticket) => ticket.state === 'en_espera' || ticket.state === 'notificado')); setError(null); } catch (reason) { setError(translateWorkerBarberError(reason instanceof Error ? reason.message : '')); } finally { setIsLoading(false); } }, []); useFocusEffect(useCallback(() => { void refresh(); }, [refresh]));
  async function call(ticket: WorkerTicket) { if (process.env.EXPO_PUBLIC_SKIP_AUTH === '1') { setError(null); return; } setIsCalling(ticket.ticketId); try { await callMyNextTicket(ticket.queueId); await refresh(); } catch (reason) { setError(translateWorkerBarberError(reason instanceof Error ? reason.message : '')); } finally { setIsCalling(null); } }
  return <WorkerScreenContainer activeNavigation="queue"><ScrollView contentContainerStyle={workerUiStyles.page}><View style={styles.heading}><WorkerText variant="eyebrow" color={workerColors.teal}>Operación en vivo</WorkerText><WorkerText variant="title">Cola de espera</WorkerText><WorkerText color={workerColors.muted}>Solo aparecen turnos que puedes atender.</WorkerText></View><View style={styles.summary}><WorkerText variant="label">{tickets.length} turnos disponibles</WorkerText><WorkerPill label={availability === 'disponible' ? 'LISTO PARA LLAMAR' : availability === 'fuera_de_turno' ? 'FUERA DE TURNO' : 'OCUPADO'} tone={availability === 'disponible' ? 'teal' : 'neutral'} /></View>{isLoading && <View accessibilityRole="progressbar" style={workerUiStyles.card}><ActivityIndicator color={workerColors.teal} /><WorkerText color={workerColors.muted}>Actualizando cola compatible…</WorkerText></View>}{error && <View style={[workerUiStyles.card, { backgroundColor: workerColors.errorContainer }]}><WorkerText variant="label" color={workerColors.error}>No pudimos actualizar la cola</WorkerText><WorkerText color={workerColors.error}>{error}</WorkerText><WorkerButton label="Reintentar" tone="secondary" onPress={() => void refresh()} /></View>}{!isLoading && !error && availability === 'fuera_de_turno' && <Empty label="Estás fuera de turno" detail="Marca tu disponibilidad en En vivo para llamar turnos." />}{!isLoading && !error && availability !== 'fuera_de_turno' && tickets.length === 0 && <Empty label="No hay turnos compatibles" detail="Los nuevos turnos compatibles aparecerán aquí." />}{tickets.map((ticket) => <Pressable key={ticket.ticketId} accessibilityRole="button" accessibilityLabel={`Llamar turno ${ticket.visibleCode}`} disabled={availability !== 'disponible' || isCalling !== null} onPress={() => void call(ticket)} style={({ pressed }) => [workerUiStyles.card, styles.ticket, { opacity: pressed || availability !== 'disponible' ? .65 : 1 }]}><View style={workerUiStyles.split}><WorkerText variant="metric">{ticket.visibleCode}</WorkerText><WorkerPill label={ticket.state === 'notificado' ? 'NOTIFICADO' : 'EN ESPERA'} tone={ticket.state === 'notificado' ? 'teal' : 'neutral'} /></View><WorkerText variant="headline">{ticket.serviceName || ticket.queueName}</WorkerText><WorkerText color={workerColors.muted}>{ticket.queueName}</WorkerText>{ticket.requestedBarberName && <WorkerText color={workerColors.muted}>Solicitó: {ticket.requestedBarberName}</WorkerText>}<WorkerText variant="label" color={workerColors.teal}>{isCalling === ticket.ticketId ? 'Llamando…' : availability === 'disponible' ? 'Llamar turno' : 'Marca disponibilidad para llamar'}</WorkerText></Pressable>)}<WorkerButton label="Agregar cliente presencial" onPress={() => router.push('/(app)/worker-walk-in')} /></ScrollView></WorkerScreenContainer>;
}
function Empty({ label, detail }: { label: string; detail: string }) { return <View style={workerUiStyles.card}><WorkerText variant="headline">{label}</WorkerText><WorkerText color={workerColors.muted}>{detail}</WorkerText></View>; }
const styles = StyleSheet.create({ heading: { gap: 6 }, summary: { alignItems: 'center', backgroundColor: workerColors.low, borderRadius: 12, flexDirection: 'row', justifyContent: 'space-between', padding: 12 }, ticket: { gap: 8 } });
