import { useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { ScrollView, StyleSheet, View } from 'react-native';

import { WorkerPill, WorkerText, workerColors, workerUiStyles } from '@/components/worker/worker-ui';
import { WorkerScreenContainer } from '@/components/worker/worker-screen-container';
import { getWorkerHistory, type WorkerHistoryEntry } from '@/features/queue/worker-barber-api';

export default function WorkerHistoryScreen() {
  const [entries, setEntries] = useState<WorkerHistoryEntry[]>([]); const [error, setError] = useState<string | null>(null);
  useFocusEffect(useCallback(() => { void getWorkerHistory().then((next) => { setEntries(next); setError(null); }).catch(() => setError('No pudimos cargar tu historial para la barbería seleccionada.')); }, []));
  const completed = entries.filter((entry) => entry.state === 'finalizado').length; const absent = entries.length - completed;
  return <WorkerScreenContainer activeNavigation="history"><ScrollView contentContainerStyle={workerUiStyles.page}><View style={styles.heading}><WorkerText variant="eyebrow" color={workerColors.teal}>Historial de operación</WorkerText><WorkerText variant="title">Tus atenciones</WorkerText><WorkerText color={workerColors.muted}>Registros de la barbería seleccionada.</WorkerText></View><View style={styles.range}><WorkerText variant="label">Historial disponible</WorkerText><WorkerPill label="TODOS LOS REGISTROS" /></View><View style={styles.metrics}><Metric label="COMPLETADOS" value={completed} color={workerColors.teal} /><Metric label="AUSENTES" value={absent} color={workerColors.error} /><Metric label="REGISTROS" value={entries.length} color={workerColors.ink} /></View><WorkerText variant="headline">Actividad reciente</WorkerText>{error ? <View style={[workerUiStyles.card, { backgroundColor: workerColors.errorContainer }]}><WorkerText variant="label" color={workerColors.error}>{error}</WorkerText></View> : entries.length === 0 ? <View accessible accessibilityLabel="Sin registros de historial" style={[workerUiStyles.card, styles.empty]}><WorkerText variant="headline">Aún no hay atenciones</WorkerText><WorkerText color={workerColors.muted}>Los turnos finalizados o ausentes aparecerán aquí.</WorkerText></View> : entries.map((entry) => <View key={entry.ticketId} style={[workerUiStyles.card, styles.entry]}><View style={[styles.code, { backgroundColor: entry.state === 'finalizado' ? workerColors.ink : workerColors.errorContainer }]}><WorkerText variant="label" color={entry.state === 'finalizado' ? '#FFFFFF' : workerColors.error}>{entry.visibleCode}</WorkerText></View><View style={styles.entryCopy}><WorkerText variant="headline">{entry.serviceName || entry.queueName}</WorkerText><WorkerText color={workerColors.muted}>{entry.queueName}</WorkerText></View><WorkerPill label={entry.state === 'finalizado' ? 'COMPLETADO' : 'AUSENTE'} tone={entry.state === 'finalizado' ? 'teal' : 'error'} /></View>)}</ScrollView></WorkerScreenContainer>;
}
function Metric({ label, value, color }: { label: string; value: number; color: string }) { return <View style={[workerUiStyles.card, styles.metric]}><WorkerText variant="eyebrow" color={workerColors.muted}>{label}</WorkerText><WorkerText variant="metric" color={color}>{value}</WorkerText></View>; }
const styles = StyleSheet.create({ heading: { gap: 6 }, range: { alignItems: 'center', backgroundColor: workerColors.low, borderRadius: 12, flexDirection: 'row', justifyContent: 'space-between', padding: 12 }, metrics: { flexDirection: 'row', gap: 8 }, metric: { flex: 1, gap: 4, padding: 12 }, empty: { gap: 8 }, entry: { alignItems: 'center', flexDirection: 'row', gap: 10 }, code: { alignItems: 'center', borderRadius: 8, justifyContent: 'center', minHeight: 46, paddingHorizontal: 8 }, entryCopy: { flex: 1, gap: 2 } });
