import { useFocusEffect, router } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { AuthButton, AuthErrorMessage } from '@/components/auth/auth-ui';
import { AuthField } from '@/components/auth/auth-field';
import { WorkerScreenContainer, workerScreenStyles } from '@/components/worker/worker-screen-container';
import { createMyWalkInTicket, getWorkerQueues } from '@/features/queue/worker-barber-api';
import { useTheme } from '@/hooks/use-theme';

export default function WorkerWalkInScreen() {
  const theme = useTheme(); const [queues, setQueues] = useState<Array<{ queueId: string; name: string }>>([]); const [queueId, setQueueId] = useState<string | null>(null); const [name, setName] = useState(''); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const load = useCallback(() => { void getWorkerQueues().then((next) => { setQueues(next); setQueueId((current) => current && next.some((queue) => queue.queueId === current) ? current : next[0]?.queueId ?? null); }).catch(() => setError('No pudimos cargar las filas de la barbería seleccionada.')); }, []);
  useFocusEffect(load);
  async function submit() { if (!queueId) return; setLoading(true); setError(null); try { setNotice(`Turno creado: ${await createMyWalkInTicket(queueId, name)}`); setName(''); } catch { setError('No pudimos crear el turno presencial. Verifica la barbería seleccionada e intenta nuevamente.'); } finally { setLoading(false); } }
  return <WorkerScreenContainer activeNavigation="live"><ScrollView contentContainerStyle={[workerScreenStyles.page, { backgroundColor: theme.background }]} keyboardShouldPersistTaps="handled"><View style={styles.heading}><Text style={[workerScreenStyles.eyebrow, { color: '#0D7A75' }]}>Registro rápido</Text><Text style={[workerScreenStyles.title, { color: theme.text }]}>Nuevo cliente presencial</Text><Text style={[workerScreenStyles.detail, { color: theme.textSecondary }]}>Agrega un turno real a la cola de tu barbería seleccionada.</Text></View><View style={styles.speed}><Text style={{ color: '#0D7A75', fontWeight: '700' }}>Registro ágil</Text><Text style={{ color: theme.textSecondary }}>El turno se crea con la posición que defina la cola.</Text></View><View style={[workerScreenStyles.card, { backgroundColor: theme.backgroundElement, borderColor: theme.border }]}><Text style={[workerScreenStyles.sectionTitle, { color: theme.text }]}>Fila de atención</Text><View style={styles.queueList}>{queues.map((queue) => <Pressable key={queue.queueId} accessibilityRole="radio" accessibilityState={{ selected: queue.queueId === queueId }} onPress={() => setQueueId(queue.queueId)} style={[styles.queueOption, { borderColor: queue.queueId === queueId ? '#0E1E2E' : theme.border, backgroundColor: queue.queueId === queueId ? '#0E1E2E' : theme.background }]}><Text style={{ color: queue.queueId === queueId ? '#FFFFFF' : theme.text, fontWeight: '700' }}>{queue.name}</Text></Pressable>)}</View><AuthField label="Nombre o referencia del cliente" value={name} onChangeText={setName} placeholder="Ej. Carlos Méndez" editable={!loading} /><AuthButton label="Asignar turno" onPress={() => void submit()} disabled={!queueId || loading} isLoading={loading} />{notice && <Text accessibilityRole="alert" style={{ color: '#0D7A75', fontWeight: '700' }}>{notice}</Text>}</View><AuthErrorMessage message={error} /><AuthButton label="Volver a En vivo" variant="secondary" onPress={() => router.replace('/(app)/worker')} /></ScrollView></WorkerScreenContainer>;
}

const styles = StyleSheet.create({ heading: { gap: 6 }, speed: { backgroundColor: '#F2EDE9', borderRadius: 8, gap: 3, padding: 12 }, queueList: { gap: 8 }, queueOption: { borderRadius: 8, borderWidth: 1, minHeight: 48, justifyContent: 'center', paddingHorizontal: 14 } });
